# Generated by Django 5.2.8 on 2025-12-17 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_board_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer_id',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_id',
            field=models.ManyToManyField(blank=True, related_name='assignee_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer_id',
            field=models.ManyToManyField(blank=True, related_name='reviewer_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
