# Generated by Django 5.2.8 on 2025-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
