# Generated by Django 5.2.8 on 2025-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_board_app', '0002_alter_board_members_alter_board_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('content', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('status', models.TextField(default='to_do', max_length=20)),
                ('priority', models.TextField(blank=True, max_length=20)),
                ('reviewer_id', models.TextField(blank=True, max_length=20)),
                ('assignee_id', models.TextField(blank=True, max_length=20)),
                ('due_date', models.DateField()),
                ('board', models.TextField()),
            ],
        ),
    ]
