# Generated by Django 5.2.8 on 2025-12-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_board_app', '0002_remove_task_assignee_id_remove_task_reviewer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanmind_board_app.board'),
        ),
    ]
