# Generated by Django 5.2.3 on 2025-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('reviewer', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
