# Generated by Django 5.2.3 on 2025-07-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0002_rename_assignee_id_task_assignees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
