# Generated by Django 5.2.3 on 2025-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0003_comment'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='board', to='kanMind_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='user_auth_app.userprofile'),
        ),
    ]
