# Generated by Django 5.2.3 on 2025-07-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0004_remove_task_assignees_alter_task_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
    ]
