# Generated by Django 5.2.3 on 2025-06-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0004_remove_board_member_remove_task_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='member',
            new_name='members',
        ),
    ]
