# Generated by Django 5.2.3 on 2025-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0005_rename_member_board_members'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='board', to='kanMind_app.task'),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='board', to='user_auth_app.userprofile'),
        ),
    ]
