# Generated by Django 5.2.3 on 2025-06-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0006_board_tasks_alter_board_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
