# Generated by Django 5.2.3 on 2025-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0006_task_reviewer'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees_id',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='user_auth_app.userprofile'),
        ),
    ]
