# Generated by Django 5.2.3 on 2025-06-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0007_remove_board_members_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanMind_app.board'),
        ),
    ]
