# Generated by Django 5.2.3 on 2025-07-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0007_rename_reviewer_task_reviewer_id_task_assignees_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignees_id',
            new_name='assignee_id',
        ),
    ]
