# Generated by Django 5.2.3 on 2025-06-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0008_rename_assignee_task_assignee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee_id',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
