# Generated by Django 5.2.3 on 2025-07-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0008_rename_assignees_id_task_assignee_id'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee_id',
            field=models.ManyToManyField(blank=True, related_name='assignee_tasks', to='user_auth_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_tasks', to='user_auth_app.userprofile'),
        ),
    ]
