# Generated by Django 5.2.3 on 2025-07-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0009_alter_task_assignee_id_alter_task_reviewer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
    ]
