# Generated by Django 5.2.3 on 2025-06-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0009_remove_task_comments_remove_task_assignee_id_and_more'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='board', to='user_auth_app.userprofile'),
        ),
    ]
