# Generated by Django 5.2.3 on 2025-06-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0012_comment_content_task_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
    ]
