# Generated by Django 5.2.3 on 2025-07-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0014_alter_task_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
    ]
