# Generated by Django 5.2.3 on 2025-07-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0015_rename_assignee_id_task_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assignee_id',
        ),
    ]
