# Generated by Django 5.2.3 on 2025-06-30 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0017_remove_task_comments_comment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 30, 11, 17, 2, 504435, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
