# Generated by Django 5.2.3 on 2025-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0018_remove_task_reviewer_id_task_reviewer_id'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reviewer_id',
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer_id',
            field=models.ManyToManyField(blank=True, related_name='reviewer_tasks', to='user_auth_app.userprofile'),
        ),
    ]
