# Generated by Django 5.2.3 on 2025-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0019_remove_task_reviewer_id_task_reviewer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='to_do', max_length=20, null=True),
        ),
    ]
