# Generated by Django 5.2.3 on 2025-06-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanMind_app', '0019_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
